variable "s3_bucketname" {}
variable "s3_acls" {}
variable "s3_attach_policy" {}
variable "s3_attach_deny_insecure_transport_policy" {}
variable "s3_attach_require_latest_tls_policy" {}
variable "s3_block_public_acls" {}
variable "s3_block_public_policy" {}
variable "s3_ignore_public_acls" {}
variable "s3_restrict_public_buckets" {}
variable "s3_bucket_ownership" {}